#!/bin/sh
#heroku create inmans --buildpack heroku/python 
# pipreqs ./ --force  # in oprder to create requirements txt

# pipreqs /home/cappittall/Documents/Said/inmansdj --force

git add .
git commit -m "Deployin my inmanns doc. new"

git push heroku master --force

heroku run python manage.py migrate
