#!/bin/sh
cd /home/cappittall/Documents/Said/inmansdj
export DJANGO_SETTINGS_MODULE=inmansdj.settings
python manage.py makemigrations api
python manage.py migrate
daphne -b 0.0.0.0 -p 8000 inmansdj.asgi:application -v2

