# Generated by Django 4.1 on 2022-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_products_alter_orders_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.IntegerField(default=0),
        ),
    ]
