# Generated by Django 4.1 on 2022-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orders_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.services', verbose_name='service'),
        ),
    ]
