# Generated by Django 4.1 on 2022-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orders_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='charge',
            field=models.FloatField(default=0.27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='orders',
            name='remains',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='start_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
