# Generated by Django 4.1 on 2022-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orders_charge_orders_currency_orders_remains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='comm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
