# Generated by Django 4.1 on 2022-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_services_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='charge',
            field=models.FloatField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='interval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='remains',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='runs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='In progress', max_length=20, null=True),
        ),
    ]
