# Generated by Django 4.1 on 2022-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orders_charge_alter_orders_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='remains',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
