# Generated by Django 4.1 on 2022-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orders_remains_alter_services_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
