# Generated by Django 4.1 on 2022-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
