# Generated by Django 4.1.5 on 2023-01-16 11:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_balancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprices',
            name='followerCount',
            field=models.CharField(choices=[(api.models.ServicePrices.FollowCount['YUZ'], '0-100'), (api.models.ServicePrices.FollowCount['BESYUZ'], '100-500'), (api.models.ServicePrices.FollowCount['BIN'], '500-1000'), (api.models.ServicePrices.FollowCount['UCBIN'], '1000-3000'), (api.models.ServicePrices.FollowCount['BESBIN'], '3000-5000'), (api.models.ServicePrices.FollowCount['BESBINUSTU'], '5000- ??')], default=api.models.ServicePrices.FollowCount['YUZ'], max_length=50),
        ),
    ]
